### ISSUE TITLE
Disk usage is not showing in Grafana dashboards for Kubernetes

### ISSUE THREAD

**Issue by einari** [dolittle-platform/home#105]
child of #71

**Comment by einari** [comment]
child of #71

**Comment by einari** [comment]
I guess this dashboard has it all:
https://monitoring.dolittle.studio/d/6DLLkuKiz/k8s-cluster-monitoring-new?refresh=10s&orgId=1

**Comment by woksin** [comment]
Yeah, I would just use that one
