### ISSUE TITLE
Fix cluster disk usage metric in Grafana / Prometheus / Kubernetes

### ISSUE THREAD

**Issue by einari** [dolittle-platform/home#84]
child of #71

The cluster disk usage is not showing numbers - it shows `N/A`- not very useful

**Comment by woksin** [comment]
Seems like this issue is related to this issue on the grafa kubernetes-app https://github.com/grafana/kubernetes-app/issues/13 

Apparently having a punctation mark in the name of a node confuses the plugin, it seems like...
