### ISSUE TITLE
Add worldping to Grafana

### ISSUE THREAD

**Issue by einari** [dolittle-platform/home#92]
child of https://github.com/dolittle-platform/home/issues/71

Add WorldPing to Grafana to be able to monitor exposed endpoints from the outside. 

We can use WorldPing with the Free tier to begin with and gain experience.

https://grafana.com/cloud/worldping

The pattern we're looking to follow is this:
https://docs.microsoft.com/en-us/azure/architecture/patterns/health-endpoint-monitoring

**Comment by woksin** [comment]
worldping up and running on monitoring.dolittle.studio
